package com.truesitesync.field.ui.diary

import android.content.Context
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.truesitesync.field.data.model.DprMeasurement
import com.truesitesync.field.data.model.DprOverhead
import java.io.File
import java.io.FileOutputStream
import java.text.DecimalFormat

/**
 * Renders a Daily Progress Report to a PDF using the platform PdfDocument, so it
 * works fully offline with no external library — mirroring the web app's
 * downloadable DPR (header, measurements table, overheads table, totals).
 */
object DprPdf {

    private const val PAGE_W = 595   // A4 @ 72dpi
    private const val PAGE_H = 842
    private const val MARGIN = 36f
    private val money = DecimalFormat("#,##0.##")
    private fun n(d: Double) = if (d == 0.0) "" else money.format(d)

    fun generate(context: Context, f: DiaryForm): File {
        val doc = PdfDocument()
        val title = Paint().apply { isAntiAlias = true; textSize = 16f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD) }
        val label = Paint().apply { isAntiAlias = true; textSize = 9f; color = 0xFF64748B.toInt() }
        val body = Paint().apply { isAntiAlias = true; textSize = 10f; color = 0xFF0F172A.toInt() }
        val head = Paint().apply { isAntiAlias = true; textSize = 8.5f; typeface = Typeface.DEFAULT_BOLD }
        val cell = Paint().apply { isAntiAlias = true; textSize = 8.5f }
        val rule = Paint().apply { color = 0xFFCBD5E1.toInt(); strokeWidth = 0.7f }

        val ctx = Ctx(doc)
        ctx.newPage()

        // ── Header ──
        ctx.canvas.drawText("Daily Progress Report", MARGIN, ctx.y, title); ctx.y += 22f
        val hdr = buildList {
            add("Date: ${f.date}")
            if (f.weather.isNotBlank()) add("Weather: ${f.weather}")
            if (f.area.isNotBlank()) add("Area: ${f.area}")
        }.joinToString("    ")
        ctx.canvas.drawText(hdr, MARGIN, ctx.y, body); ctx.y += 16f
        val man = "Manpower  Skilled: ${f.manpowerSkilled.ifBlank { "0" }}   Unskilled: ${f.manpowerUnskilled.ifBlank { "0" }}"
        ctx.canvas.drawText(man, MARGIN, ctx.y, body); ctx.y += 16f
        if (f.equipment.isNotBlank()) { ctx.canvas.drawText("Equipment: ${f.equipment}", MARGIN, ctx.y, body); ctx.y += 16f }
        if (f.workDone.isNotBlank()) { ctx.y += 4f; ctx.wrap("Work done: ${f.workDone}", body); }
        if (f.hindrance.isNotBlank()) { ctx.wrap("Hindrance: ${f.hindrance}", body) }
        ctx.y += 10f

        // ── Measurements table ──
        if (f.measurements.isNotEmpty()) {
            ctx.section("Measurements", title.apply { textSize = 12f })
            drawMeasurements(ctx, f.measurements, head, cell, rule)
            ctx.y += 4f
            ctx.canvas.drawText("Measurement total: ${money.format(f.measurementTotal)}", MARGIN, ctx.y, head); ctx.y += 18f
        }

        // ── Overheads table ──
        if (f.overheads.isNotEmpty()) {
            ctx.section("Overheads / Resources", title.apply { textSize = 12f })
            drawOverheads(ctx, f.overheads, head, cell, rule)
            ctx.y += 4f
            ctx.canvas.drawText("Overhead total: ${money.format(f.overheadTotal)}", MARGIN, ctx.y, head); ctx.y += 18f
        }

        // Footer note
        label.textSize = 8f
        ctx.canvas.drawText("Generated by True Site Sync", MARGIN, PAGE_H - 20f, label)

        doc.finishPage(ctx.page)
        val dir = File(context.cacheDir, "dpr").apply { mkdirs() }
        val file = File(dir, "DPR_${f.date}_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun drawMeasurements(ctx: Ctx, rows: List<DprMeasurement>, head: Paint, cell: Paint, rule: Paint) {
        // columns: Description | Loc | Nos | L | B | H | Qty | Rate | Amount
        val xs = floatArrayOf(MARGIN, 170f, 250f, 290f, 330f, 370f, 410f, 470f, 520f)
        val headers = arrayOf("Description", "Loc", "Nos", "L", "B", "H", "Qty", "Rate", "Amount")
        ctx.ensure(24f)
        headers.forEachIndexed { i, h -> ctx.canvas.drawText(h, xs[i], ctx.y, head) }
        ctx.y += 4f; ctx.canvas.drawLine(MARGIN, ctx.y, PAGE_W - MARGIN, ctx.y, rule); ctx.y += 12f
        rows.forEach { m ->
            ctx.ensure(14f)
            ctx.canvas.drawText(clip(m.description.ifBlank { m.code }, 24), xs[0], ctx.y, cell)
            ctx.canvas.drawText(clip(m.location, 12), xs[1], ctx.y, cell)
            ctx.canvas.drawText(n(m.nos), xs[2], ctx.y, cell)
            ctx.canvas.drawText(n(m.l), xs[3], ctx.y, cell)
            ctx.canvas.drawText(n(m.b), xs[4], ctx.y, cell)
            ctx.canvas.drawText(n(m.h), xs[5], ctx.y, cell)
            ctx.canvas.drawText(money.format(m.qty), xs[6], ctx.y, cell)
            ctx.canvas.drawText(n(m.rate), xs[7], ctx.y, cell)
            ctx.canvas.drawText(n(m.amount), xs[8], ctx.y, cell)
            ctx.y += 13f
        }
    }

    private fun drawOverheads(ctx: Ctx, rows: List<DprOverhead>, head: Paint, cell: Paint, rule: Paint) {
        val xs = floatArrayOf(MARGIN, 320f, 400f, 480f)
        val headers = arrayOf("Resource / Activity", "Qty", "Rate", "Cost")
        ctx.ensure(24f)
        headers.forEachIndexed { i, h -> ctx.canvas.drawText(h, xs[i], ctx.y, head) }
        ctx.y += 4f; ctx.canvas.drawLine(MARGIN, ctx.y, PAGE_W - MARGIN, ctx.y, rule); ctx.y += 12f
        rows.forEach { o ->
            ctx.ensure(14f)
            ctx.canvas.drawText(clip(o.resource.ifBlank { o.activity }, 46), xs[0], ctx.y, cell)
            ctx.canvas.drawText(n(o.qty), xs[1], ctx.y, cell)
            ctx.canvas.drawText(n(o.rate), xs[2], ctx.y, cell)
            ctx.canvas.drawText(n(o.cost), xs[3], ctx.y, cell)
            ctx.y += 13f
        }
    }

    private fun clip(s: String, max: Int) = if (s.length <= max) s else s.take(max - 1) + "…"

    /** Cursor that owns the current page and vertical position, with pagination. */
    private class Ctx(val doc: PdfDocument) {
        lateinit var page: PdfDocument.Page
        val canvas get() = page.canvas
        var y = MARGIN
        private var num = 0

        fun newPage() {
            if (num > 0) doc.finishPage(page)
            num++
            page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, num).create())
            y = MARGIN
        }

        fun ensure(space: Float) { if (y + space > PAGE_H - MARGIN) newPage() }

        fun section(titleText: String, paint: Paint) {
            ensure(24f)
            canvas.drawText(titleText, MARGIN, y, paint); y += 16f
        }

        fun wrap(text: String, paint: Paint, maxWidth: Float = PAGE_W - 2 * MARGIN) {
            val words = text.split(" ")
            var line = ""
            for (w in words) {
                val test = if (line.isEmpty()) w else "$line $w"
                if (paint.measureText(test) > maxWidth) {
                    ensure(14f); canvas.drawText(line, MARGIN, y, paint); y += 13f; line = w
                } else line = test
            }
            if (line.isNotEmpty()) { ensure(14f); canvas.drawText(line, MARGIN, y, paint); y += 13f }
        }
    }
}
