package com.truesitesync.field.ui.abstracts

import android.content.Context
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream
import java.text.DecimalFormat

/** Renders a work abstract to a PDF via the platform PdfDocument (offline). */
object AbstractPdf {
    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private const val MARGIN = 36f
    private val fmt = DecimalFormat("#,##0.##")
    private fun n(d: Double) = if (d == 0.0) "" else fmt.format(d)
    private fun clip(s: String, max: Int) = if (s.length <= max) s else s.take(max - 1) + "…"

    fun generate(context: Context, f: AbstractForm): File {
        val doc = PdfDocument()
        val title = Paint().apply { isAntiAlias = true; textSize = 16f; typeface = Typeface.DEFAULT_BOLD }
        val body = Paint().apply { isAntiAlias = true; textSize = 10f }
        val head = Paint().apply { isAntiAlias = true; textSize = 8.5f; typeface = Typeface.DEFAULT_BOLD }
        val cell = Paint().apply { isAntiAlias = true; textSize = 8.5f }
        val rule = Paint().apply { color = 0xFFCBD5E1.toInt(); strokeWidth = 0.7f }

        var num = 0
        var page = start(doc, ++num)
        var canvas = page.canvas
        var y = MARGIN

        canvas.drawText("Work Abstract", MARGIN, y, title); y += 20f
        canvas.drawText(
            listOfNotNull(f.abstractNum, f.date.ifBlank { null }, f.area.ifBlank { null }).joinToString("    "),
            MARGIN, y, body,
        ); y += 18f

        // # | Code | Description | Unit | Qty | Rate | Amount
        val xs = floatArrayOf(MARGIN, 60f, 120f, 330f, 375f, 435f, 500f)
        val headers = arrayOf("#", "Code", "Description", "Unit", "Qty", "Rate", "Amount")
        fun header() {
            headers.forEachIndexed { i, h -> canvas.drawText(h, xs[i], y, head) }
            y += 4f; canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule); y += 12f
        }
        header()

        f.items.forEachIndexed { i, it ->
            if (y + 14f > PAGE_H - MARGIN) {
                doc.finishPage(page); page = start(doc, ++num); canvas = page.canvas; y = MARGIN; header()
            }
            canvas.drawText("${i + 1}", xs[0], y, cell)
            canvas.drawText(clip(it.code, 9), xs[1], y, cell)
            canvas.drawText(clip(it.desc, 32), xs[2], y, cell)
            canvas.drawText(clip(it.uom, 6), xs[3], y, cell)
            canvas.drawText(n(it.qty), xs[4], y, cell)
            canvas.drawText(n(it.rate), xs[5], y, cell)
            canvas.drawText(n(it.amount), xs[6], y, cell)
            y += 13f
        }

        y += 6f; canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule); y += 14f
        canvas.drawText("Grand total: ${fmt.format(f.total)}", MARGIN, y, head)
        canvas.drawText("Generated by True Site Sync", MARGIN, PAGE_H - 20f, cell)

        doc.finishPage(page)
        val dir = File(context.cacheDir, "dpr").apply { mkdirs() }
        val file = File(dir, "Abstract_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun start(doc: PdfDocument, num: Int): PdfDocument.Page =
        doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, num).create())
}
