package com.truesitesync.field.ui.measurement

import android.content.Context
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.truesitesync.field.data.model.SheetEntry
import java.io.File
import java.io.FileOutputStream
import java.text.DecimalFormat

/** Renders a measurement sheet to a PDF via the platform PdfDocument (offline). */
object SheetPdf {
    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private const val MARGIN = 36f
    private val fmt = DecimalFormat("#,##0.##")
    private fun n(d: Double) = if (d == 0.0) "" else fmt.format(d)
    private fun clip(s: String, max: Int) = if (s.length <= max) s else s.take(max - 1) + "…"

    fun generate(context: Context, f: SheetForm): File {
        val doc = PdfDocument()
        val title = Paint().apply { isAntiAlias = true; textSize = 16f; typeface = Typeface.DEFAULT_BOLD }
        val head = Paint().apply { isAntiAlias = true; textSize = 8.5f; typeface = Typeface.DEFAULT_BOLD }
        val cell = Paint().apply { isAntiAlias = true; textSize = 8.5f }
        val rule = Paint().apply { color = 0xFFCBD5E1.toInt(); strokeWidth = 0.7f }

        var num = 0
        var page = startPage(doc, ++num)
        var canvas = page.canvas
        var y = MARGIN

        canvas.drawText(clip(f.name.ifBlank { "Measurement Sheet" }, 60), MARGIN, y, title); y += 22f

        // columns: # | Description | Code | Unit | Nos | L | B | H | Qty
        val xs = floatArrayOf(MARGIN, 60f, 250f, 300f, 345f, 385f, 425f, 465f, 510f)
        val headers = arrayOf("#", "Description", "Code", "Unit", "Nos", "L", "B", "H", "Qty")
        fun drawHeader() {
            headers.forEachIndexed { i, h -> canvas.drawText(h, xs[i], y, head) }
            y += 4f; canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule); y += 12f
        }
        drawHeader()

        f.entries.forEachIndexed { i, e ->
            if (y + 14f > PAGE_H - MARGIN) {
                doc.finishPage(page); page = startPage(doc, ++num); canvas = page.canvas; y = MARGIN; drawHeader()
            }
            canvas.drawText("${i + 1}", xs[0], y, cell)
            canvas.drawText(clip(e.description, 30), xs[1], y, cell)
            canvas.drawText(clip(e.code, 8), xs[2], y, cell)
            canvas.drawText(clip(e.uom, 6), xs[3], y, cell)
            canvas.drawText(n(e.nos), xs[4], y, cell)
            canvas.drawText(n(e.l), xs[5], y, cell)
            canvas.drawText(n(e.b), xs[6], y, cell)
            canvas.drawText(n(e.h), xs[7], y, cell)
            canvas.drawText(fmt.format(e.qty), xs[8], y, cell)
            y += 13f
        }

        y += 6f
        canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, rule); y += 14f
        canvas.drawText("Total quantity: ${fmt.format(f.total)}", MARGIN, y, head)

        canvas.drawText("Generated by True Site Sync", MARGIN, PAGE_H - 20f, cell)

        doc.finishPage(page)
        val dir = File(context.cacheDir, "dpr").apply { mkdirs() }
        val file = File(dir, "Measurement_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun startPage(doc: PdfDocument, num: Int): PdfDocument.Page =
        doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, num).create())
}
